import test from 'node:test';
import assert from 'node:assert/strict';
import {patientDiets,dietPdf} from '../src/diets.mjs';

const patient = {name:'PAT-1'};
const chart = {name:'Vitiligo',diet_chart_name:'Vitiligo Diet Chart',custom_items:[{item_code:'CREAM'}],custom_diet_chart_pdf:'/files/diet.pdf'};
const invoice = (name,extra={}) => ({name,patient:'PAT-1',docstatus:1,posting_date:'2026-10-08',items:[{item_code:'CREAM',item_name:'Cream',qty:1}],...extra});
function setup({charts=[chart],invoices=[invoice('INV-1')],encounters=[]}={}) {
  const docs={'Diet Chart':structuredClone(charts),'Sales Invoice':invoices,'Patient Encounter':encounters};
  const calls=[];
  return {url:'https://erp.test',calls,docs,
    async list(type,filters,fields,{offset,limit}) {
      const rows=docs[type].filter(d=>Object.entries(filters).every(([key,value])=>{
        if(!Array.isArray(value)) return d[key]===value;
        if(value[0]==='<') return d[key]<value[1];
        if(value[0]==='is') return Boolean(d[key]);
        throw Error('Unexpected filter');
      }));
      return rows.slice(offset,offset+limit).map(d=>Object.fromEntries(fields.map(f=>[f,d[f]])));
    },
    async get(type,name) {return structuredClone(docs[type].find(d=>d.name===name));},
    async request(path) {calls.push(path);return new Response('%PDF-test');},
  };
}

test('exact ERP item mappings select chart once across repeated purchases',async()=>{
  const erp=setup({invoices:[invoice('I1'),invoice('I2')],charts:[{...chart,custom_items:[{item_code:'CREAM'},{item_code:'CREAM'}]}]});
  const {items}=await patientDiets(erp,patient);
  assert.equal(items.length,1);assert.equal(items[0].autoGenerated,true);
  assert.deepEqual(items[0].matchedItems,[{code:'CREAM',name:'Cream'}]);
  assert.equal(items[0].hasPdf,true);
  assert.equal(items[0].custom_diet_chart_pdf,undefined);
});

test('draft, cancelled, unrelated item and another patient do not grant charts',async()=>{
  const erp=setup({invoices:[invoice('draft',{docstatus:0}),invoice('cancelled',{docstatus:2}),
    invoice('other',{patient:'PAT-2'}),invoice('title-match',{items:[{item_code:'OTHER',item_name:'CREAM',qty:1}]})]});
  assert.deepEqual(await patientDiets(erp,patient),{items:[]});
});

test('full returns revoke automatic charts; partial returns retain them',async()=>{
  const returned=invoice('RET',{is_return:1,items:[{item_code:'CREAM',qty:-1}]});
  assert.equal((await patientDiets(setup({invoices:[invoice('I'),returned]}),patient)).items.length,0);
  assert.equal((await patientDiets(setup({invoices:[invoice('I'),invoice('I2'),returned]}),patient)).items.length,1);
});

test('manual assignments remain and take precedence over automatic matching',async()=>{
  const erp=setup({encounters:[{name:'ENC1',patient:'PAT-1',docstatus:0,diet_chart:'Vitiligo',encounter_date:'2026-10-07'},
    {name:'ENC2',patient:'PAT-1',docstatus:1,diet_chart:'Vitiligo',encounter_date:'2026-10-08'}]});
  const result=await patientDiets(erp,patient);
  assert.equal(result.items.length,1);assert.equal(result.items[0].autoGenerated,false);
  assert.equal(result.items[0].date,'2026-10-08');assert.equal(result.items[0].source,'encounter');
  erp.docs['Sales Invoice']=[];
  assert.equal((await patientDiets(erp,patient)).items.length,1);
});

test('invoices are paginated rather than silently omitting older purchases',async()=>{
  const invoices=Array.from({length:105},(_,i)=>invoice(`I${i}`,{items:i===104?[{item_code:'CREAM',qty:1}]:[]}));
  assert.equal((await patientDiets(setup({invoices}),patient)).items.length,1);
});

test('changed item mappings are reflected on next read',async()=>{
  const erp=setup();assert.equal((await patientDiets(erp,patient)).items.length,1);
  erp.docs['Diet Chart'][0].custom_items=[];
  assert.equal((await patientDiets(erp,patient)).items.length,0);
});

test('PDF download verifies patient entitlement and does not expose arbitrary charts',async()=>{
  const erp=setup();
  await assert.rejects(dietPdf(erp,{name:'PAT-2'},'Vitiligo'),{status:404});
  await assert.rejects(dietPdf(erp,patient,'Hair'),{status:404});
  assert.equal(erp.calls.length,0);
  const pdf=await dietPdf(erp,patient,'Vitiligo');assert.equal(await pdf.text(),'%PDF-test');
  assert.ok(erp.calls[0].startsWith('/api/method/frappe.handler.download_file?'));
});

test('PDF proxy rejects external or non-file URLs before sending ERP credentials',async()=>{
  for(const url of ['https://other.test/diet.pdf','//other.test/diet.pdf','/api/method/anything.pdf','/files/diet.pdf?x=1']) {
    const erp=setup({charts:[{...chart,custom_diet_chart_pdf:url}]});
    await assert.rejects(dietPdf(erp,patient,'Vitiligo'),{status:503});assert.equal(erp.calls.length,0);
  }
});

test('a login HTML response is not relayed as a PDF',async()=>{
  const erp=setup();erp.request=async()=>new Response('<html>Login</html>');
  await assert.rejects(dietPdf(erp,patient,'Vitiligo'),{status:502});
});
