import {requireValue} from './errors.mjs';

async function all(erp, type, filters, fields) {
  const rows = [];
  for (let offset = 0; ; offset += 100) {
    const page = await erp.list(type, filters, fields, {offset, limit:100, order:'name asc'});
    rows.push(...page);
    if (page.length < 100) return rows;
  }
}

export async function patientDiets(erp, patient) {
  const [links, chartRows] = await Promise.all([
    all(erp,'Patient Encounter',{patient:patient.name,docstatus:['<',2],diet_chart:['is','set']},
      ['name','diet_chart','encounter_date']),
    all(erp,'Diet Chart',{},['name']),
  ]);
  const charts = [];
  for (let i=0;i<chartRows.length;i+=4) {
    charts.push(...await Promise.all(chartRows.slice(i,i+4).map(row=>erp.get('Diet Chart',row.name))));
  }
  const mappedCodes = new Set(charts.flatMap(c=>(c.custom_items || []).map(i=>i.item_code)).filter(Boolean));
  const purchases = new Map();
  if (mappedCodes.size) {
    // Patient-scoped invoices only: a shared Customer must not grant clinical access.
    const rows = await all(erp,'Sales Invoice',{patient:patient.name,docstatus:1},['name']);
    for (let i=0;i<rows.length;i+=4) {
      const docs = await Promise.all(rows.slice(i,i+4).map(row=>erp.get('Sales Invoice',row.name)));
      for (const invoice of docs) {
        if (invoice.patient !== patient.name || invoice.docstatus !== 1) continue;
        for (const item of invoice.items || []) {
          if (!mappedCodes.has(item.item_code)) continue;
          const quantity = Number(item.stock_qty ?? item.qty);
          if (!Number.isFinite(quantity)) continue;
          const previous = purchases.get(item.item_code) || {quantity:0,code:item.item_code,name:item.item_name || item.item_code,date:''};
          previous.quantity += invoice.is_return ? -Math.abs(quantity) : quantity;
          if (!invoice.is_return && quantity > 0 && String(invoice.posting_date) > previous.date) {
            previous.date = invoice.posting_date;
          }
          purchases.set(item.item_code,previous);
        }
      }
    }
  }
  const items = [];
  for (const chart of charts) {
    const manual = links.filter(l=>l.diet_chart === chart.name)
      .sort((a,b)=>String(b.encounter_date).localeCompare(String(a.encounter_date)))[0];
    const matched = [...new Set((chart.custom_items || []).map(i=>i.item_code))]
      .map(code=>purchases.get(code)).filter(item=>item?.quantity > 0);
    if (!manual && !matched.length) continue;
    items.push({id:chart.name,title:chart.diet_chart_name || chart.name,
      date:manual?.encounter_date || matched.map(i=>i.date).sort().at(-1),
      autoGenerated:!manual,source:manual?'encounter':'purchase',
      matchedItems:manual?[]:matched.map(({code,name})=>({code,name})),
      instructions:chart.instructions || '',allowedFoods:chart.allowed_foods || '',restrictedFoods:chart.restricted_foods || '',
      hasPdf:Boolean(chart.custom_diet_chart_pdf),
    });
  }
  return {items:items.sort((a,b)=>String(b.date).localeCompare(String(a.date)))};
}

export async function dietPdf(erp, patient, id) {
  // Re-evaluate ownership, returns and mappings on every download.
  const {items} = await patientDiets(erp,patient);
  requireValue(items.some(chart=>chart.id === id && chart.hasPdf),'Diet chart not found',404);
  const chart = await erp.get('Diet Chart',id);
  let file;
  try { file = new URL(chart.custom_diet_chart_pdf,erp.url); } catch {}
  requireValue(file && file.origin === new URL(erp.url).origin && !file.username && !file.password &&
    /^\/(private\/)?files\/.+\.pdf$/i.test(file.pathname) && !file.search && !file.hash,
    'Diet chart PDF must be uploaded to ERP. Please contact the clinic.',503);
  const response = await erp.request(`/api/method/frappe.handler.download_file?${new URLSearchParams({file_url:file.pathname})}`,{raw:true});
  const bytes = Buffer.from(await response.arrayBuffer());
  requireValue(bytes.subarray(0,5).toString() === '%PDF-','Diet chart PDF is unavailable. Please contact the clinic.',502);
  return new Response(bytes,{headers:{'Content-Type':'application/pdf'}});
}
